### PR TITLE
moved sql start to non-blocking mode

### PR DESCRIPTION
**Pull request by arindamnayak**
Signed-off-by: Arindam Nayak <arindam.nayak@outlook.com>.

Here is the change description: Earlier when mysqlctl process starts/stops it uses `Exec.Cmd.Run` which waits till the command completes. Now it will use `Exec.Cmd.Start` which will not wait till command completes, rather it will spawn required number of mysqlctl procs and then it will wait till all started (using `proc.Wait`), this way mysqlctl procs starts or stop kind of parallel manner. This reduced the test time from 90 second to almost 50 second.

### CODE REVIEW

**Review by ajeetj — COMMENTED** [review]
LGTM

**Comment by deepthi** [comment]
can you rebase? e2e test is failing with etcd installed_version error.

**Review by deepthi — APPROVED** [review]
LGTM

**Comment by arindamnayak** [comment]
@morgo , is there any reason why `e2e test cluster` fails in planetscale repo with same error for every PR? But it works correctly in vitessio.

**Pull request merged**
