### PR TITLE
Misc GO tests for vtgatev3

### PR DESCRIPTION
**Pull request by ajeetj**
Misc VTGATE3 test cases

- TruncateTable
- ScatterLimit
- VindexFunc
- AnalyzeTable

Signed-off-by: Ajeet jain ajeet@planetscale.com

### CODE REVIEW

**Comment by ajeetj** [comment]
Old comments from previous PR

**ajeetj**
I was not able to find a good way to update the TransactionMode for a VtGate connection. Can you help me with that?

By looking at the code it should have happened if we update the cluster.Config.TransactionMode value.


**deepthi**
It seems like cluster.Config is only read while starting the VtComboProcess:
https://github.com/vitessio/vitess/blob/master/go/vt/vttest/local_cluster.go#L252

So I don't think it can be changed on the fly like this.

I took a quick look at the python code, but it isn't obvious how this is being done there. You will need to dig into the cursor code in https://github.com/vitessio/vitess/blob/master/py/vtdb/vtgate_cursor.py

**Comment by ajeetj** [comment]
@deepthi TrasactionMode will require a lot of configuration on how we setup VtGate. So I have moved those to a new file and will work on those when new cluster is up.

**Comment by deepthi** [comment]
Looks good. I can do a more thorough review when you think this is ready for merge.

**Comment by ajeetj** [comment]
> Looks good. I can do a more thorough review when you think this is ready for merge.

@deepthi This is good to merge, I forgot to remove the DO NOT MERGE tage after I separate the TransactionMode testcases.

**Review by deepthi — APPROVED** [review]

**Pull request merged**
