### PR TITLE
Tabletmanager2 test cases in GO using cluster

### PR DESCRIPTION
**Pull request by ajeetj**
Reference python code: https://github.com/vitessio/vitess/blob/master/test/tabletmanager2.py

TestStartSlaveUntilAfter is flaky and stuck in `master INSERT` after we `StopSlave`. I tried everything but not able to figure out why it stuck. Can you also take a look?

### CODE REVIEW

**Comment by deepthi** [comment]
I'm having difficulty running this locally. Either it fails immediately, or it hangs.
In both cases, none of the debug statements (`fmt.Println`) is printed.
I checked out the branch tal_tabletmanager2, and this is what I get when I do `go test`
```
~/go/src/vitess.io/vitess/go/test/endtoend/tabletmanager$ go test -v
...
proto: no coders for int
proto: no encoder for ValueSize int [GetProperties]
E1031 17:59:06.815339    2501 cluster_process.go:113] exit status 255
2019-10-31 17:59:06.816956 N | pkg/osutil: received terminated signal, shutting down...
2019-10-31 17:59:06.817058 I | etcdserver: skipped leadership transfer for single member cluster
E1031 17:59:06.818728    2501 cluster_process.go:288] signal: terminated
exit status 1
FAIL	vitess.io/vitess/go/test/endtoend/tabletmanager	1.049s
```
OR
```
proto: no coders for int
proto: no encoder for ValueSize int [GetProperties]
2019-10-31 18:00:58.388488 N | pkg/osutil: received interrupt signal, shutting down...
2019-10-31 18:00:58.389076 I | etcdserver: skipped leadership transfer for single member cluster
WARNING: 2019/10/31 18:00:58 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp: operation was canceled"; Reconnecting to {localhost:31821 0  <nil>}
WARNING: 2019/10/31 18:00:58 grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
signal: interrupt
FAIL	vitess.io/vitess/go/test/endtoend/tabletmanager	101.246s
```

**Comment by ajeetj** [comment]
> I'm having difficulty running this locally. Either it fails immediately, or it hangs.
> In both cases, none of the debug statements (`fmt.Println`) is printed.
> I checked out the branch tal_tabletmanager2, and this is what I get when I do `go test`
> 
> ```
> ~/go/src/vitess.io/vitess/go/test/endtoend/tabletmanager$ go test -v
> ...
> proto: no coders for int
> proto: no encoder for ValueSize int [GetProperties]
> E1031 17:59:06.815339    2501 cluster_process.go:113] exit status 255
> 2019-10-31 17:59:06.816956 N | pkg/osutil: received terminated signal, shutting down...
> 2019-10-31 17:59:06.817058 I | etcdserver: skipped leadership transfer for single member cluster
> E1031 17:59:06.818728    2501 cluster_process.go:288] signal: terminated
> exit status 1
> FAIL	vitess.io/vitess/go/test/endtoend/tabletmanager	1.049s
> ```
> 
> OR
> 
> ```
> proto: no coders for int
> proto: no encoder for ValueSize int [GetProperties]
> 2019-10-31 18:00:58.388488 N | pkg/osutil: received interrupt signal, shutting down...
> 2019-10-31 18:00:58.389076 I | etcdserver: skipped leadership transfer for single member cluster
> WARNING: 2019/10/31 18:00:58 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp: operation was canceled"; Reconnecting to {localhost:31821 0  <nil>}
> WARNING: 2019/10/31 18:00:58 grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
> signal: interrupt
> FAIL	vitess.io/vitess/go/test/endtoend/tabletmanager	101.246s
> ```

For me, it always hangs after the 1st print statement. 
Screen Shot 2019-11-01 at 3 38 32 PM

I have also synced this branch with the latest cluster code so the etcd process should not cause any problems. But if tests stuck in between then I do the following two things.
1.  manually kill the process `kill -9 $(pgrep -fl vtdataroot | awk '{print $1}')`
2. empty the vtdataroot folder.

**Comment by ajeetj** [comment]
this is what i see in master tablet logs
```
2019-11-01T10:33:11.741769Z 2 [Note] Aborted connection 2 to db: 'unconnected' user: 'root' host: 'localhost' (Got an error reading communication packets)
2019-11-01T10:33:12.126447Z 6 [Note] Aborted connection 6 to db: 'unconnected' user: 'vt_dba' host: 'localhost' (Got an error reading communication packets)
2019-11-01T10:33:12.128850Z 8 [Note] Aborted connection 8 to db: 'unconnected' user: 'vt_dba' host: 'localhost' (Got an error reading communication packets)
2019-11-01T10:33:12.204068Z 10 [Note] Aborted connection 10 to db: 'unconnected' user: 'vt_dba' host: 'localhost' (Got an error reading communication packets)
2019-11-01T10:33:18.477324Z 19 [Note] Semi-sync replication initialized for transactions.
2019-11-01T10:33:18.477924Z 19 [Note] Semi-sync replication enabled on the master.
2019-11-01T10:33:18.478009Z 0 [Note] Starting ack receiver thread
2019-11-01T10:33:18.488530Z 22 [Note] Unknown database 'vt_ks'
2019-11-01T10:33:18.489532Z 23 [Note] Unknown database 'vt_ks'
2019-11-01T10:33:18.490006Z 24 [Note] Unknown database 'vt_ks'
2019-11-01T10:33:18.576666Z 27 [Note] Start binlog_dump to master_thread_id(27) slave_server(1946235800), pos(, 4)
2019-11-01T10:33:18.576700Z 27 [Note] Start semi-sync binlog_dump to slave (server_id: 1946235800), pos(, 4)
2019-11-01T10:33:18.688236Z 28 [Note] Aborted connection 28 to db: 'unconnected' user: 'vt_dba' host: 'localhost' (Got an error reading communication packets)
2019-11-01T10:33:18.821596Z 35 [Note] Aborted connection 35 to db: 'vt_ks' user: 'vt_dba' host: 'localhost' (Got an error reading communication packets)
2019-11-01T10:33:22.227550Z 36 [Note] Aborted connection 36 to db: 'vt_ks' user: 'vt_app' host: 'localhost' (Got an error reading communication packets)
2019-11-01T10:33:22.237013Z 40 [Note] Aborted connection 40 to db: 'vt_ks' user: 'vt_filtered' host: 'localhost' (Got an error reading communication packets)
2019-11-01T10:33:24.112176Z 41 [Note] Aborted connection 41 to db: 'vt_ks' user: 'vt_dba' host: 'localhost' (Got an error reading communication packets)
2019-11-01T10:33:24.118274Z 0 [ERROR] /usr/local/mysql/bin/mysqld: Got an error reading communication packets
2019-11-01T10:33:54.133641Z 27 [Note] Stop semi-sync binlog_dump to slave (server_id: 1946235800)
2019-11-01T10:33:54.137839Z 27 [Note] Aborted connection 27 to db: 'unconnected' user: 'vt_repl' host: '::1' (failed on flush_net())
2019-11-01T10:34:24.048302Z 17 [Note] Aborted connection 17 to db: 'unconnected' user: 'vt_dba' host: 'localhost' (Got an error reading communication packets)
2019-11-01T10:34:24.050294Z 18 [Note] Aborted connection 18 to db: 'unconnected' user: 'vt_dba' host: 'localhost' (Got an error reading communication packets)
2019-11-01T10:34:24.050735Z 19 [Note] Aborted connection 19 to db: 'unconnected' user: 'vt_dba' host: 'localhost' (Got an error reading communication packets)
2019-11-01T10:34:24.051095Z 20 [Note] Aborted connection 20 to db: 'unconnected' user: 'vt_dba' host: 'localhost' (Got an error reading communication packets)
2019-11-01T10:34:24.051447Z 21 [Note] Aborted connection 21 to db: 'unconnected' user: 'vt_dba' host: 'localhost' (Got an error reading communication packets)

```

It looks like when I `StopSlave` then master also got stopped.

**Comment by ajeetj** [comment]
@morgo 
Hi Morgan, Can you take a look at this PR especially `TestStartSlaveUntilAfter` test? 
The test hangs at `insert` command after I exec `StopSlave` command. Surprisingly the test passed a few times but hangs the rest of the time. 
We are not able to figure out why is that weird behavior.

**Comment by ajeetj** [comment]
It worked after I disabled `semi_sync` as suggested by @morgo .
I will make the required changes in the code and push a fix.

**Comment by ajeetj** [comment]
@morgo @deepthi 
These test cases are working now after disabling the Semi-Sync. 

Python test does have the semi-sync enabled. How they are working is still a mystery. 
Ref: https://github.com/planetscale/vitess/blob/master/test/tablet.py#L457

**Review by deepthi — APPROVED** [review]

**Pull request merged**
