### PR TITLE
[DO Not Merge] VTGATE SPLIT QUERY endtoend test cases in GO

### PR DESCRIPTION
**Pull request by ajeetj**
VTGATE SPLIT QUERY endtoend test cases in GO using the new cluster. 

@deepthi 
Question: Split query hangs in the terminal, we try to exec command in another window but got the same result.  What can we do to solve this? 

Screen Shot 2019-10-22 at 11 52 24 AM

### CODE REVIEW

**Comment by deepthi** [comment]
I tried running this test, and also clustertest in this branch.
They both hang while starting vtctld:

```
proto: no coders for int
proto: no encoder for ValueSize int [GetProperties]
Starting vtctld server on port : 26506
SIGQUIT: quit
PC=0x460271 m=0 sigcode=0
...
goroutine 1 [chan receive, 9 minutes]:
vitess.io/vitess/go/test/endtoend/cluster.(*VtctldProcess).Setup(0xc000023810, 0x96a04b, 0x5, 0x1, 0x1)
	/home/deepthi/go/src/vitess.io/vitess/go/test/endtoend/cluster/vtctld_process.go:115 +0x945
vitess.io/vitess/go/test/endtoend/cluster.(*LocalProcessCluster).StartTopo(0xc000023680, 0x98aa10, 0xc000023680)
	/home/deepthi/go/src/vitess.io/vitess/go/test/endtoend/cluster/cluster_process.go:95 +0x4ba
vitess.io/vitess/go/test/endtoend/clustertest.TestMain.func1(0xc00013a100, 0x0)
	/home/deepthi/go/src/vitess.io/vitess/go/test/endtoend/clustertest/main_test.go:68 +0xd2
vitess.io/vitess/go/test/endtoend/clustertest.TestMain(0xc00013a100)
	/home/deepthi/go/src/vitess.io/vitess/go/test/endtoend/clustertest/main_test.go:90 +0x82
main.main()
	_testmain.go:48 +0x13e
```

There is an earlier error message:
```
2019-10-27 17:07:57.533884 E | etcdmain: forgot to set Type=notify in systemd service file?
```
Is this relevant?

**Comment by deepthi** [comment]
The log file location needs to be fixed. If I try to re-run the test, it fails with:
`mkdir /home/deepthi/go/vtdataroot/tmp: file exists`

We need to implement something similar to what the python tests did: create a separate vt_xxx directory for each test and use that.

**Comment by ajeetj** [comment]
> The log file location needs to be fixed. If I try to re-run the test, it fails with:
> `mkdir /home/deepthi/go/vtdataroot/tmp: file exists`
> 
> We need to implement something similar to what the python tests did: create a separate vt_xxx directory for each test and use that.

Most of these things Arindam has already fixed. Give me a day and I will move this one to the new cluster.

**Comment by ajeetj** [comment]
@deepthi Moved this code against the new cluster. 
Reference PR: https://github.com/planetscale/vitess/pull/24

**Pull request closed without merging**
